config/routes.rb
Rails.application.routes.draw do
  resources :powers
  resources :planets
  resources :aliens
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/alien.rb
class Alien < ApplicationRecord
    belongs_to :planet

    has_many :alien_powers
    has_many :powers, through: :alien_powers

    validates_presence_of :name
end

app/models/alien_power.rb
class AlienPower < ApplicationRecord
  belongs_to :alien
  belongs_to :power
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/planet.rb
class Planet < ApplicationRecord
end

app/models/power.rb
class Power < ApplicationRecord

    has_many :alien_powers
    has_many :aliens, through: :alien_powers
end

app/controllers/aliens_controller.rb
class AliensController < ApplicationController
  before_action :set_alien, only: %i[ show edit update destroy ]

  # GET /aliens or /aliens.json
  def index
    @aliens = Alien.all
  end

  # GET /aliens/1 or /aliens/1.json
  def show
  end

  # GET /aliens/new
  def new
    @alien = Alien.new
  end

  # GET /aliens/1/edit
  def edit
  end

  # POST /aliens or /aliens.json
  def create
    @alien = Alien.new(alien_params)

    respond_to do |format|
      if @alien.save
        format.html { redirect_to @alien, notice: "Alien was successfully created." }
        format.json { render :show, status: :created, location: @alien }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @alien.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /aliens/1 or /aliens/1.json
  def update
    puts params
    respond_to do |format|
      if @alien.update(alien_params)
        format.html { redirect_to @alien, notice: "Alien was successfully updated." }
        format.json { render :show, status: :ok, location: @alien }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @alien.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /aliens/1 or /aliens/1.json
  def destroy
    @alien.destroy
    respond_to do |format|
      format.html { redirect_to aliens_url, notice: "Alien was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_alien
      @alien = Alien.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def alien_params
      params.require(:alien).permit(:name, :age, :planet_id, :powers_ids => [])
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/planets_controller.rb
class PlanetsController < ApplicationController
  before_action :set_planet, only: %i[ show edit update destroy ]

  # GET /planets or /planets.json
  def index
    @planets = Planet.all
  end

  # GET /planets/1 or /planets/1.json
  def show
  end

  # GET /planets/new
  def new
    @planet = Planet.new
  end

  # GET /planets/1/edit
  def edit
  end

  # POST /planets or /planets.json
  def create
    @planet = Planet.new(planet_params)

    respond_to do |format|
      if @planet.save
        format.html { redirect_to @planet, notice: "Planet was successfully created." }
        format.json { render :show, status: :created, location: @planet }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @planet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /planets/1 or /planets/1.json
  def update
    respond_to do |format|
      if @planet.update(planet_params)
        format.html { redirect_to @planet, notice: "Planet was successfully updated." }
        format.json { render :show, status: :ok, location: @planet }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @planet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /planets/1 or /planets/1.json
  def destroy
    @planet.destroy
    respond_to do |format|
      format.html { redirect_to planets_url, notice: "Planet was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_planet
      @planet = Planet.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def planet_params
      params.require(:planet).permit(:name)
    end
end

app/controllers/powers_controller.rb
class PowersController < ApplicationController
  before_action :set_power, only: %i[ show edit update destroy ]

  # GET /powers or /powers.json
  def index
    @powers = Power.all
  end

  # GET /powers/1 or /powers/1.json
  def show
  end

  # GET /powers/new
  def new
    @power = Power.new
  end

  # GET /powers/1/edit
  def edit
  end

  # POST /powers or /powers.json
  def create
    @power = Power.new(power_params)

    respond_to do |format|
      if @power.save
        format.html { redirect_to @power, notice: "Power was successfully created." }
        format.json { render :show, status: :created, location: @power }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @power.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /powers/1 or /powers/1.json
  def update
    respond_to do |format|
      if @power.update(power_params)
        format.html { redirect_to @power, notice: "Power was successfully updated." }
        format.json { render :show, status: :ok, location: @power }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @power.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /powers/1 or /powers/1.json
  def destroy
    @power.destroy
    respond_to do |format|
      format.html { redirect_to powers_url, notice: "Power was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_power
      @power = Power.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def power_params
      params.require(:power).permit(:name)
    end
end

app/helpers/aliens_helper.rb
module AliensHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/planets_helper.rb
module PlanetsHelper
end

app/helpers/powers_helper.rb
module PowersHelper
end

app/views/aliens/_form.html.erb
<%= form_with(model: alien) do |form| %>
  <% if alien.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(alien.errors.count, "error") %> prohibited this alien from being saved:</h2>

      <ul>
        <% alien.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

        
  

  <div class="field">
    <%= form.label :Planeta %>
    <%= form.select :planet_id, Planet.all.map { |index| [index.name.to_s, index.id]},
    {include_blank: 'Selecione o Planeta'},
    { class: "form-control", required: true } %>
  </div>




  <div class="field">
    <%= form.label :Nome %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :Idade %>
    <%= form.number_field :age %>
  </div>

  <div class="field">
  <%= form.label :Poderes %>
  <%= collection_check_boxes(:alien, :power_ids, Power.all, :id, :name) %>
</div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/aliens/edit.html.erb
<h1>Editando Alienígenas</h1>

<%= render 'form', alien: @alien %>

<div class="menuBack">
  <%= link_to 'Show', @alien %>
  <%= link_to 'Voltar', aliens_path %>
</div>

app/views/aliens/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Alienígenas</h1>

<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th>Idade</th>
      <th>Planeta</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @aliens.each do |alien| %>
      <tr>
        <td><%= alien.name %></td>
        <td><%= alien.age %></td>
        <td><%= alien.try(:planet).try(:name) %></td>
        <td><%= link_to 'Ver', alien %></td>
        <td><%= link_to 'Editar', edit_alien_path(alien) %></td>
        <td><%= link_to 'Deletar', alien, method: :delete, data: { confirm: 'Você tem certeza?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Novo Alien', new_alien_path %>

app/views/aliens/new.html.erb
<h1>Novo Alienígena</h1>

<%= render 'form', alien: @alien %>

<%= link_to 'Voltar', aliens_path %>

app/views/aliens/show.html.erb
<p id="notice"><%= notice %></p>



<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th>Idade</th>
      <th>Planeta</th>
    </tr>
  </thead>

  <tbody>
      <tr>
        <td><%= @alien.name %></td>
        <td><%= @alien.age %></td>
        <td><%= @alien.try(:planet).try(:name) %></td>
      </tr>
  </tbody>
</table>

<div class="menuBack">
  <%= link_to 'Editar', edit_alien_path(@alien) %>
  <%= link_to 'Voltar', aliens_path %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SpaceRails</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    
    <div id="menu">
      <%= link_to "ALIENS", aliens_path %>
      <%= link_to "PLANETAS", planets_path %>
      <%= link_to "PODERES", powers_path %>
    </div>

    <div id="contents">
      <%= yield %>
    </div>
  </body>
</html>

app/views/planets/_form.html.erb
<%= form_with(model: planet) do |form| %>
  <% if planet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(planet.errors.count, "error") %> prohibited this planet from being saved:</h2>

      <ul>
        <% planet.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :Nome %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/planets/edit.html.erb
<h1>Editando Planeta</h1>

<%= render 'form', planet: @planet %>

<div class="menuBack">
  <%= link_to 'Edit', @planet %>
  <%= link_to 'Voltar', planets_path %>
</div>

app/views/planets/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Planetas</h1>

<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @planets.each do |planet| %>
      <tr>
        <td><%= planet.name %></td>
        <td><%= link_to 'Show', planet %></td>
        <td><%= link_to 'Editar', edit_planet_path(planet) %></td>
        <td><%= link_to 'Deletar', planet, method: :delete, data: { confirm: 'Você tem certeza?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Novo Planeta', new_planet_path %>

app/views/planets/new.html.erb
<h1>Novo Planeta</h1>

<%= render 'form', planet: @planet %>

<%= link_to 'Back', planets_path %>

app/views/planets/show.html.erb
<p id="notice"><%= notice %></p>


<table>
  <thead>
    <tr>
      <th>Nome</th>
    </tr>
  </thead>

  <tbody>
      <tr>
        <td><%= @planet.name %></td>
      </tr>
  </tbody>
</table>

<div class="menuBack">
  <%= link_to 'Editar', edit_planet_path(@planet) %>
  <%= link_to 'Voltar', planets_path %>
</div>

app/views/powers/_form.html.erb
<%= form_with(model: power) do |form| %>
  <% if power.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(power.errors.count, "error") %> prohibited this power from being saved:</h2>

      <ul>
        <% power.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :Nome %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/powers/edit.html.erb
<h1>Editando Poderes</h1>

<%= render 'form', power: @power %>

<div class="menuBack">
  <%= link_to 'Show', @power %>
  <%= link_to 'Voltar', powers_path %>
</div>

app/views/powers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Poderes</h1>

<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @powers.each do |power| %>
      <tr>
        <td><%= power.name %></td>
        <td><%= link_to 'Show', power %></td>
        <td><%= link_to 'Editar', edit_power_path(power) %></td>
        <td><%= link_to 'Deletar', power, method: :delete, data: { confirm: 'Você tem certeza?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Novo Poder', new_power_path %>

app/views/powers/new.html.erb
<h1>Novo Power</h1>

<%= render 'form', power: @power %>

<%= link_to 'Voltar', powers_path %>

app/views/powers/show.html.erb
<p id="notice"><%= notice %></p>

<table>
  <thead>
    <tr>
      <th>Nome</th>
    </tr>
  </thead>

  <tbody>
      <tr>
        <td><%= @power.name %></td>
      </tr>
  </tbody>
</table>

<div class="menuBack">
  <%= link_to 'Editar', edit_power_path(@power) %>
  <%= link_to 'Voltar', powers_path %>
</div>